<a href="https://colab.research.google.com/github/first-penguin-hub/rabbit_challenge/blob/main/1_1_forward_propagation_after.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 準備

## Google Colab 用の処理

下記を実行します
- ドライブのマウント
- ノートブックファイルと同じフォルダへの移動

Googleドライブのマイドライブ を基準に DNN_code/DNN_code_colab_day1 フォルダを置くことを仮定しています。必要に応じて，パスを変更してください．

In [3]:
# Google Colab での実行かを調べる
import sys
import os
ENV_COLAB = True  if 'google.colab' in sys.modules else False

# google drive のマウント
if ENV_COLAB:
  from google.colab import drive
  drive.mount('/content/drive')
  os.chdir('/content/drive/My Drive/StudyAI/DNN_code_colab_day1/notebook')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

In [4]:
import sys
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定

# importと関数定義

In [5]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [6]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
#W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = np.array(0.5)

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1]
 [0.2]]
shape: (2, 1)

*** バイアス ***
0.5
shape: ()

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[1.3]
shape: (1,)

*** 中間層出力 ***
[1.3]
shape: (1,)



# 順伝播（単層・複数ユニット）

In [7]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3,0],
    [0.2, 0.3, 0.4, 0.5],
    [0.3, 0.4, 0.5, 1],
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)

#  総入力
u = np.dot(W, x) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape: (3, 4)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[1.8 2.2 2.6]
shape: (3,)

*** 中間層出力 ***
[0.85814894 0.90024951 0.93086158]
shape: (3,)



# 順伝播（3層・複数ユニット）

In [8]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}

    input_layer_size = 3
    hidden_layer_size_1=10
    hidden_layer_size_2=5
    output_layer_size = 4

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1,hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size_1)
    network['b2'] =  np.random.rand(hidden_layer_size_2)
    network['b3'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):

    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2

    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3

    # 出力層の総出力
    y = u3

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("中間層出力2", z2)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2. 4.]
shape: (3,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.88890829 0.3583654  0.18999964 0.21189521 0.05468317 0.33790204
  0.911627   0.11922741 0.09425236 0.68328897]
 [0.19252727 0.85691996 0.42970655 0.38728817 0.87184716 0.56739957
  0.18354443 0.80787663 0.64110619 0.03761926]
 [0.41142599 0.64634811 0.59605662 0.96816138 0.88086511 0.55257011
  0.65469382 0.80966031 0.37764297 0.80270191]]
shape: (3, 10)

*** 重み2 ***
[[1.24502715e-02 2.81836209e-01 6.54112917e-01 8.62600641e-01
  3.91340893e-01]
 [4.77700222e-01 2.11357417e-01 2.36399115e-01 1.91887721e-01
  6.57592726e-01]
 [4.38301433e-01 3.74123849e-01 9.67907932e-01 6.88386286e-01
  5.88837216e-01]
 [1.22055290e-01 1.81812217e-01 2.16723778e-01 3.37899616e-01
  9.99076041e-01]
 [4.99705766e-01 5.22643609e-01 8.25147324e-01 3.11273578e-01
  8.98985903e-01]
 [1.27285135e-01 2.36290236e-03 7.22270644e-01 9.92468960e-01
  1.71407332e-01]
 [5.54513370e-01 1.08520883e-01 1.88428141e-01 9.85878387e-01
  1.54392437e-

In [9]:
np.random.rand(3, 3)

array([[0.91742711, 0.6213713 , 0.80461664],
       [0.05140397, 0.49207441, 0.38920188],
       [0.36237761, 0.57989765, 0.76856112]])

# 多クラス分類（2-3-4ネットワーク）

In [10]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}

    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 6

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):

    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']

    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2

    # 出力値
    y = functions.softmax(u2)

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.15893422 0.03307208 0.41044208 0.84400158 0.18754268 0.67540454
  0.46536843 0.8028335  0.10299024 0.98816503 0.18636238 0.67442333
  0.8414876  0.01398127 0.55685186 0.29766014 0.98536596 0.40886229
  0.69540206 0.47270723 0.7132955  0.03069417 0.11675636 0.33641013
  0.50660072 0.82426516 0.96526889 0.57063554 0.46372001 0.7318646
  0.72350078 0.72998532 0.17149326 0.1967805  0.92935646 0.13130219
  0.82822706 0.1799506  0.90924995 0.07502207 0.33764125 0.55961282
  0.16388035 0.93958961 0.30890435 0.29338409 0.31436161 0.98129643
  0.68905798 0.3480368 ]
 [0.71184403 0.60787509 0.6259019  0.96779431 0.97057734 0.28610514
  0.0358624  0.55346124 0.43539036 0.59063581 0.37055212 0.62191996
  0.61594463 0.55313363 0.14933414 0.43789471 0.3555457  0.44629192
  0.57012904 0.00813245 0.13280048 0.18099697 0.09587722 0.73666009
  0.56082927 0.55028585 0.61531954 0.41098615 0.49180731 0.64518865
  0.79424412 0.53592944 0.9562105  0.93352884 0.43383602 

# 回帰（2-3-2ネットワーク）

In [11]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 2

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")

    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.13906795 0.20962689 0.48291217 0.02946521 0.64914839 0.51112144
  0.23645449 0.22233689 0.67104008 0.91269796 0.22782366 0.99701935
  0.68989857 0.24687964 0.80874556 0.65451331 0.62611151 0.99835914
  0.84944149 0.34360089 0.31735692 0.50709937 0.3329739  0.18240997
  0.3366055  0.02193735 0.91198654 0.29411684 0.39226372 0.0152609
  0.45317822 0.8156034  0.31941997 0.1987317  0.6560465  0.4891921
  0.86947854 0.38269812 0.16905865 0.56960413 0.37695817 0.73504044
  0.96224402 0.25533716 0.97187174 0.38605175 0.28782958 0.38936584
  0.61908574 0.07377082]
 [0.21785053 0.88154939 0.22475066 0.86285468 0.97873922 0.24320923
  0.43774076 0.86412648 0.0236033  0.62720365 0.03813781 0.21175377
  0.28250574 0.51602851 0.00549625 0.95985765 0.80132656 0.46808924
  0.69372623 0.48243642 0.88979212 0.18572432 0.37272288 0.16237753
  0.01160985 0.74136781 0.79070871 0.68926097 0.16948124 0.12837494
  0.54023501 0.23091319 0.42995718 0.21308595 0.48780851 0

# 2値分類（2-3-1ネットワーク）

In [12]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)

    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[1.81886277 5.08655708 7.91400756 2.01706433 5.06306725 7.81439324
 1.64791721 4.70160434 7.02544707 2.13150464]
shape: (10,)

*** 中間層出力1 ***
[1.81886277 5.08655708 7.91400756 2.01706433 5.06306725 7.81439324
 1.64791721 4.70160434 7.02544707 2.13150464]
shape: (10,)

*** 総入力2 ***
[24.31899064 24.63009762 16.89952939 20.14225197 18.68155464 17.46732479
 25.14803481 21.54514988 29.04160792 21.10392054 23.62168978 21.43244753
 29.5342793  17.39966887 25.8252495  28.94925755 24.93319835 30.06335923
 31.67460718 26.82722956]
shape: (20,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 1.0

##### 結果表示 #####
*** 中間層出力 ***
[1.81886277 5.08655708 7.91400756 2.01706433 5.06306725 7.81439324
 1.64791721 4.70160434 7.02544707 2.13150464]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 交差エントロピー誤差 ***
-9.999999505838704e-08
shape: ()

